# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72326e20b9b338af33e265990fb8d73d2532b867fb961f1ee9997ca35be1315e6df681a60d297ef773be909f442464b160ec693a7309a34a49a899aa630cc34c

test:
  secret_key_base: 2321953616216df981dbf7274260f2187edc3e43226a092080169d0063d2492b128527c9cb142cf5beac021674febb357f250ebde6087996920fc61fcb8cba3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
